[build]
  publish = "dist/public"
  command = "npm install && npx vite build --config vite.config.prod.ts"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "/api"