[build]
  command = "node build-frontend.js"
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "/api"

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "/api"