[build]
  publish = "dist/public"
  command = "npm run build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "/api"