[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/medicines/*"
  to = "/.netlify/functions/medicines"
  status = 200

[[redirects]]
  from = "/api/medicines"
  to = "/.netlify/functions/medicines"
  status = 200

[[redirects]]
  from = "/api/thuoc/*"
  to = "/.netlify/functions/thuoc"
  status = 200

[[redirects]]
  from = "/api/thuoc"
  to = "/.netlify/functions/thuoc"
  status = 200

[[redirects]]
  from = "/api/statistics"
  to = "/.netlify/functions/statistics"
  status = 200

[[redirects]]
  from = "/api/prescriptions"
  to = "/.netlify/functions/prescriptions"
  status = 200

[[redirects]]
  from = "/api/patients"
  to = "/.netlify/functions/patients"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"